name: cluck_way_app
description: "A Flutter app for finding lost devices using Bluetooth."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.5.1

  go_router: ^14.2.7

  flutter_blue_plus: ^1.16.7

  permission_handler: ^11.3.1

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_local_notifications: ^18.0.1

  url_launcher: ^6.3.1

  android_intent_plus: ^4.0.3

  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:

  uses-material-design: true

  assets:
    - assets/images/
